name: 'Coverage check'
on:
    pull_request:
        branches: '*'

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: ArtiomTr/jest-coverage-report-action@v2
              id: coverage
              with:
                  output: report-markdown
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  threshold: 80
                  test-script: yarn jest
            - uses: marocchino/sticky-pull-request-comment@v2
              with:
                  message: ${{ steps.coverage.outputs.report }}