name: 'Coverage check'
on:
    pull_request:
        branches: '*'

jobs:
    coverage:
        runs-on: ubuntu-latest
        env:
            CI_JOB_NUMBER: 1
        steps:
            - uses: actions/checkout@v1
            - name: npm install
              run: npm install
            - uses: artiomtr/jest-coverage-report-action@v1.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  threshold: 80